# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Sysdig - Build, scan, push and upload sarif report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 0 * * 6'

permissions:
  contents: read

jobs:

  build:

    permissions:
      checks: write # for sysdiglabs/scan-action to publish the checks
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: env

    - name: Debug Set up secret file
      env:
        RICHARD_TESTX: ${{ secrets.RICHARD_TEST }}        
        RICHARD_TEST: ${{ secrets.RICHARD_TEST }}
      run: |
        echo ${{ secrets.RICHARD_TEST }}
        echo ${{ secrets.actions.RICHARD_TEST }}
        echo ${{ secrets.Actions.RICHARD_TEST }}
        echo $RICHARD_TESTX >> secrets.txt
        echo ${{ secrets.RICHARD_TEST }} >> secrets.txt
        echo ${{ secrets.actions.RICHARD_TEST }} >> secrets.txt
        echo ${{ secrets.Actions.RICHARD_TEST }} >> secrets.txt
        cat secrets.txt

    - name: Debug2
      run: echo ${{secrets.RICHARD_TEST}}
    - uses: actions/checkout@v3    

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64
    - name: Cache Maven packages
      uses: actions/cache@v3.0.4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn --no-transfer-progress package

    - name: Build the Docker image
      # Tag image to be built
      # Change ${{ github.repository }} variable by another image name if you want but don't forget changing also image-tag below
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest

    - name: Sysdig Secure Inline Scan
      id: scan
      uses: sysdiglabs/scan-action@768d7626a14897e0948ea89c8437dd46a814b163
      with:
        # Tag of the image to analyse. 
        # Change ${{ github.repository }} variable by another image name if you want but don't forget changing also image-tag above
        image-tag: ${{ github.repository }}:latest
        # API token for Sysdig Scanning auth
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN}}
        # Sysdig secure endpoint. Please read: https://docs.sysdig.com/en/docs/administration/saas-regions-and-ip-ranges/
        # US-East https://secure.sysdig.com
        # US-West https://us2.app.sysdig.com
        # EU      https://eu1.app.sysdig.com 
        sysdig-secure-url: https://us2.app.sysdig.com
        dockerfile-path: ./Dockerfile
        input-type: docker-daemon
        ignore-failed-scan: true
        # Sysdig inline scanner requires privileged rights
        run-as-user: root

    - uses: github/codeql-action/upload-sarif@v2
      #Upload SARIF file
      if: always()
      with:
        sarif_file: ${{ steps.scan.outputs.sarifReport }}
